### ISSUE TITLE
Dependence Problem and Bug on Archlinux

### ISSUE THREAD

**Issue by cdqz2014** [featurecat/lizzie#22]
I ran lizzie on my Archlinux, but it responsed

> ./leelaz: error while loading shared libraries: libboost_program_options.so.1.58.0: cannot open shared object file: No such file or directory
> Leelaz process ended.

However, unlike the situation on ubuntu, there is no package **libboost_program_options** on Archlinux.

I tried to replace your leelaz file with that generated on my Archlinux, then lizzie was successfully launched but with some bugs:

the game trees and winning rates did not appear correctly near the board but in my terminal instead...

**Comment by cdqz2014** [comment]
![2018-03-21-203804_1920x1080_scrot](https://user-images.githubusercontent.com/26814587/37710189-dcd9a40a-2d47-11e8-9844-98d1d5753b9c.png)

**Comment by featurecat** [comment]
Will fix in 2-3 days for 1.3

**Comment by featurecat** [comment]
Fixed. If you compile it yourself, you most likely won't experience this problem. Download the mac-linux release from https://github.com/featurecat/lizzie/releases/tag/0.3, and follow the installation instructions in the Readme.

**Comment by cdqz2014** [comment]
@featurecat However I still experience this problem...

I placed the leelaz compiled on my Archlinux in the directory of new lizzie and launched it, but the winning rate as well as gaming tree still cannot display correctly.

![2018-03-28-163638_1920x1080_scrot](https://user-images.githubusercontent.com/26814587/38018681-29745dcc-32a8-11e8-8845-8b18fc2dd392.png)

**Comment by featurecat** [comment]
and you definitely compiled it from my fork of Leela zero? not from GCP's? if so I can send you a version with more diagnostic output so we can figure it out...

**Comment by featurecat** [comment]
https://github.com/featurecat/leela-zero make sure you compile it from here.

**Comment by cdqz2014** [comment]
Oh sorry, let me try yours.

**Comment by cdqz2014** [comment]
Oh that works! Thank you for your help!

**Comment by featurecat** [comment]
yay! I'm so glad it works. what I learned from last version is, never pre compile software for Linux users, lol
